version: "3.8"

services:
  stock_app:
    build:
      context: .
      dockerfile: Dockerfile.dev  # 開発用Dockerfileを指定
    container_name: stock_app
    ports:
      - "8501:8501"
    volumes:
      - ./workspace:/app/workspace
    env_file:
      - .env

  jupyterlab:
    image: jupyter/base-notebook:latest
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
      JUPYTER_TOKEN: ""
    command: "start-notebook.sh --NotebookApp.token=''"
