# ベースイメージとして公式のPythonイメージを使用
FROM python:3.9-slim

# 必要なシステムパッケージのインストール
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    wget \
    vim \
    curl \
    tar \
    && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリを設定
WORKDIR /app

# Pythonパッケージのインストール
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# アプリケーションファイルをコピー
COPY workspace/ /app/workspace/

# ポートの開放
EXPOSE 8501 8888

# ストリームリットアプリを起動
CMD ["streamlit", "run", "/app/workspace/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
