version: "3.8"

services:
  stock_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: stock_app
    ports:
      - "8501:8501"
    volumes:
      - ./workspace:/app/workspace
    env_file:
      - .env
    command: streamlit run /app/workspace/app.py

  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./workspace:/app/workspace
    env_file:
      - .env
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      GRANT_SUDO: "yes"
      JUPYTER_TOKEN: ""
    command: "jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
