[gcp_service_account]
type = "service_account"
project_id = "dbt-analytics-engineer-435907"
private_key_id = "75a25995915e73861eb9b83f521943d986af57da"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9b/uocYnKoGLh
jXe7M/9izka6IefsoCMjWTljxWadwQqtG/5IDKPCJ1qOvUPaypCfRAniUdVTHqvK
sLK55pZB15qsl4wR9Mj+DPUf4zyHpHohy5PM+kd2QnITcXL3JapeGhCRFXG14ssD
LV0V6RXJPPc3uxQJai4XIMhdb837VvNYxd1WMWPLqCc9moIXTnkjr0Ha1yZmoqB/
sO26CpS3DFx+f8oRCBdJRTaI2i1zHJH4QPHCHLbPf5CNcMSsr+NXCH6PoKf8dV31
0gwdpYKuYigCzP4w3TMpOmowEEvEhGMHJ4n+qThPYmAMz9GI3QwDOOK1S2YPuGcI
aFmCEbRtAgMBAAECggEARN/XlAT/r5uDh/UK0JXVpwNPZLIaJAaO7/WrL3KgXf/H
FWxFlcV+roLnYlk+t+gJD9bJby8Ii+ltVUrMGFnVTIgKlPCefRLOFsv4PUk9gyWS
QAJHsPFYFQ+QcTBAt8nKeN8qIc21o4ca/4M5QlOV164iRfFvFgM0UbVaE9qn/dac
+D4DZKr1Do8y1KXVhZQFOHK2jTvVfewZe2srMj7sEKzmeOoolvo1LVAoeLd5l3zm
C47+4ywuBIK8y3KDazzK/dE7t4O4Xnr8BRHb7Kld2XB7tqJ8H1r/VTPlJA5wldWJ
oZ934CtZYUZb07FrG3KpA5kDoFOAbK/ZSJl5d/hHYwKBgQDv3jVkNvUtSOnwHM1q
Mz/jve3VeRtEMb6c89dxrT6vBMeicB99+ZslVzYyE2+e4mFQsntICaSWdYmavHAT
O/i+aQYLJHAm4cUelwN0qkBg6Lu+AHEyT1SRhqZyoq78hxC2Q/vGH+EDFn8/ss4S
qLi0tF5UGEepDQz9Skr9L4j7zwKBgQDKLYPFvBebKMa95q+I+gGbbNYkmNiOf4sp
tVigYwEQvv62b/0Erkhdqd3rj6BkJh1V6BnhKEDY1onuuTUBracIBajqkjZCSFdA
I1BjehtagHuSOkoElAVJC0/1ufCEx35OacfeU1nQXNVtRDtQQgbSl2QLUcH2J7eJ
sK07NzhvAwKBgQCF67xHfV+ZrvHdu1b8iiyLjIjy/LC6fEN+Aa4xq5YpxTNof801
WlzCllSN1MgnHyFSGrQ13hxkXK89EyRHuN4CAUT8h5WOP9L8ZzfotP1InefkBv8s
JZqDvXfE3Qtxtj8gZAh372iDftYAzGW9iTHGwkVAEmY//idYa1g+z4FdhQKBgDOJ
eqezFMlmkZLi9SgTosk96zCVDc71UEInihoIYsMkDMXwsiy5SJUnsfxUNmyRErVN
Xxt4KV+dALgr2gk9fPCckLyK3O30htlAp0NUYxik29sgpLGaEebWzWE0Ls2KFPZk
HKDd2m003Ornk78XtamFEemYw7q90Rl2QhJwNyCFAoGAcz7N83FyH1XVF3dzwDK3
C0lWlJ4JRtnbxpiUFJ9xLE0x55PHectIOVfmjcosp4J0HTiC2S/p8RDPLLokTu4A
70zVMp7XtLoBQBog3YumD6bb1tWv7CVabLvk7VqWX1d6IjsZgOAE5HL3dUfYd/yz
eIiOpRhcSbQWBlBKlvW/WMU=
-----END PRIVATE KEY-----
"""
client_email = "bigquery-gcs-integration@dbt-analytics-engineer-435907.iam.gserviceaccount.com"
client_id = "109777367763352015982"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/bigquery-gcs-integration%40dbt-analytics-engineer-435907.iam.gserviceaccount.com"
